# Generated by Django 2.2.12 on 2021-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210912_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
